import type { Candle, Side } from '../types';
export const FIB={early:61.8,preferred:68.1,second:78.6,last:88.0,stop:125.0,tp1:38.2,tp2:0.0,tp3:-23.6,minConfluence:60,entryAtrLength:14,displacementATR:0.60,retestBars:8,pivotLen:5,asia:'0000-0600',london:'0700-1000',ny:'1230-1700',dxyMaLen:50,dxyMaTouch:0.15} as const;
export type FibAnchor='Asia Low'|'Asia High'|'London Low'|'London High'|'New York Low'|'New York High'|'Previous Day Low'|'Previous Day High'|'Previous Week Low'|'Previous Week High'|'Auto Swing Low'|'Auto Swing High';
export interface FibAnchorConfig{buyStartAnchor:FibAnchor;buyEndAnchor:FibAnchor;sellStartAnchor:FibAnchor;sellEndAnchor:FibAnchor;}
export const DEFAULT_FIB_ANCHORS:FibAnchorConfig={buyStartAnchor:'Asia Low',buyEndAnchor:'Asia High',sellStartAnchor:'Asia High',sellEndAnchor:'Asia Low'};
export interface FibSignal{side:Side;entry:number;stopLoss:number;takeProfit:number;tp1:number;tp2:number;tp3:number;confidence:number;quality:string;reason:string[];state:string;orderBar:number;pullbackBar:number;}
export interface FibContext{dxy?:Candle[];confirmation?:Candle[];anchors?:Partial<FibAnchorConfig>;confirmationOffsetMs?:number;}
function rma(v:number[],n:number){const o:number[]=Array(v.length).fill(NaN);if(v.length<n)return o;let p=0;for(let i=0;i<n;i++)p+=v[i];p/=n;o[n-1]=p;for(let i=n;i<v.length;i++){p=(p*(n-1)+v[i])/n;o[i]=p;}return o;}
function atr(c:Candle[],n:number){return rma(c.map((x,i)=>i===0?x.high-x.low:Math.max(x.high-x.low,Math.abs(x.high-c[i-1].close),Math.abs(x.low-c[i-1].close))),n);}
function ema(v:number[],n:number){const k=2/(n+1);let e=v[0]??0;return v.map((x,i)=>i?(e=x*k+e*(1-k)):e);}
function buyLevel(t:number,b:number,p:number){return t-((t-b)*p/100);}
function sellLevel(t:number,b:number,p:number){return b+((t-b)*p/100);}
function session(ts:number,spec:string){const d=new Date(ts),m=d.getUTCHours()*60+d.getUTCMinutes(),p=spec.split('-'),a=Number(p[0].slice(0,2))*60+Number(p[0].slice(2)),b=Number(p[1].slice(0,2))*60+Number(p[1].slice(2));return a<=b?m>=a&&m<b:m>=a||m<b;}
function dayKey(ts:number){const d=new Date(ts);return `${d.getUTCFullYear()}-${d.getUTCMonth()+1}-${d.getUTCDate()}`;}
function weekKey(ts:number){const d=new Date(ts),day=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()-day+1);return dayKey(d.getTime());}
function previousExtremes(c:Candle[]){const days=new Map<string,Candle[]>(),weeks=new Map<string,Candle[]>();for(const x of c){const d=dayKey(x.time),w=weekKey(x.time);if(!days.has(d))days.set(d,[]);if(!weeks.has(w))weeks.set(w,[]);days.get(d)!.push(x);weeks.get(w)!.push(x);}const dk=[...days.keys()],wk=[...weeks.keys()],dc=dk.length>1?days.get(dk[dk.length-2])!:[],wc=wk.length>1?weeks.get(wk[wk.length-2])!:[];return{pdHigh:dc.length?Math.max(...dc.map(x=>x.high)):NaN,pdLow:dc.length?Math.min(...dc.map(x=>x.low)):NaN,pwHigh:wc.length?Math.max(...wc.map(x=>x.high)):NaN,pwLow:wc.length?Math.min(...wc.map(x=>x.low)):NaN};}
function latestSession(c:Candle[],spec:string){let hi=NaN,lo=NaN,key='';for(const x of c)if(session(x.time,spec)){const k=dayKey(x.time);if(k!==key){key=k;hi=x.high;lo=x.low;}else{hi=Math.max(hi,x.high);lo=Math.min(lo,x.low);}}return{hi,lo};}
function pivots(c:Candle[],n:number){let high=NaN,low=NaN;for(let i=n;i<c.length-n;i++){let ph=true,pl=true;for(let j=1;j<=n;j++){if(c[i].high<=c[i-j].high||c[i].high<c[i+j].high)ph=false;if(c[i].low>=c[i-j].low||c[i].low>c[i+j].low)pl=false;}if(ph)high=c[i].high;if(pl)low=c[i].low;}return{high,low};}
function anchor(a:FibAnchor,asia:{hi:number,lo:number},lon:{hi:number,lo:number},ny:{hi:number,lo:number},p:{pdHigh:number,pdLow:number,pwHigh:number,pwLow:number},pv:{high:number,low:number}){switch(a){case'Asia Low':return asia.lo;case'Asia High':return asia.hi;case'London Low':return lon.lo;case'London High':return lon.hi;case'New York Low':return ny.lo;case'New York High':return ny.hi;case'Previous Day Low':return p.pdLow;case'Previous Day High':return p.pdHigh;case'Previous Week Low':return p.pwLow;case'Previous Week High':return p.pwHigh;case'Auto Swing Low':return pv.low;case'Auto Swing High':return pv.high;}}
function atOrBefore(c:Candle[],time:number){let v:Candle|undefined;for(const x of c){if(x.time<=time)v=x;else break;}return v;}
function before(c:Candle[],time:number){let v:Candle|undefined;for(const x of c){if(x.time<time)v=x;else break;}return v;}
function dxyStats(dxy:Candle[]|undefined,time:number){if(!dxy?.length)return{bear:false,bull:false,volSpike:false,bearMa:false,bullMa:false};const d=atOrBefore(dxy,time),dp=before(dxy,time);const bear=!!d&&!!dp&&d.close<dp.close,bull=!!d&&!!dp&&d.close>dp.close,ds=dxy.filter(x=>x.time<=time),vols=ds.slice(-20).map(x=>x.volume),vs=vols.length?vols.reduce((a,b)=>a+b,0)/vols.length:NaN,volSpike=!!d&&Number.isFinite(vs)&&d.volume>vs*1.5,ma=ds.length>=FIB.dxyMaLen?ema(ds.map(x=>x.close),FIB.dxyMaLen).at(-1):NaN,above=!!d&&Number.isFinite(ma)&&d.close>ma,below=!!d&&Number.isFinite(ma)&&d.close<ma;return{bear,bull,volSpike,bearMa:bear&&below,bullMa:bull&&above};}
function score(c:Candle[],dxy:Candle[]|undefined,time:number,top:number,bot:number){const x=atOrBefore(c,time)??c[c.length-1],pd=previousExtremes(c),dx=dxyStats(dxy,time),mid=(top+bot)/2,pdl=Number.isFinite(pd.pdLow)&&x.low<pd.pdLow&&x.close>pd.pdLow,pdh=Number.isFinite(pd.pdHigh)&&x.high>pd.pdHigh&&x.close<pd.pdHigh;return{buy:Math.min(100,(x.close>=mid?20:0)+(dx.bear?15:0)+(dx.bearMa?10:0)+(dx.volSpike?10:0)+(pdl?15:0)+(x.close>=mid?20:0)),sell:Math.min(100,(x.close<=mid?20:0)+(dx.bull?15:0)+(dx.bullMa?10:0)+(dx.volSpike?10:0)+(pdh?15:0)+(x.close<=mid?20:0))};}
export function vaultFibSignal(c:Candle[],ctx:FibContext={}):FibSignal|null{
 if(c.length<30)return null;const ac={...DEFAULT_FIB_ANCHORS,...ctx.anchors},asia=latestSession(c,FIB.asia),lon=latestSession(c,FIB.london),ny=latestSession(c,FIB.ny),prev=previousExtremes(c),pv=pivots(c,FIB.pivotLen),bs=anchor(ac.buyStartAnchor,asia,lon,ny,prev,pv),be=anchor(ac.buyEndAnchor,asia,lon,ny,prev,pv),ss=anchor(ac.sellStartAnchor,asia,lon,ny,prev,pv),se=anchor(ac.sellEndAnchor,asia,lon,ny,prev,pv),br=Number.isFinite(bs)&&Number.isFinite(be)&&Math.abs(bs!-be!)>1e-12,sr=Number.isFinite(ss)&&Number.isFinite(se)&&Math.abs(ss!-se!)>1e-12;if(!br&&!sr)return null;const bt=br?Math.max(bs!,be!):NaN,bb=br?Math.min(bs!,be!):NaN,st=sr?Math.max(ss!,se!):NaN,sb=sr?Math.min(ss!,se!):NaN,bmid=br?(bt+bb)/2:NaN,smid=sr?(st+sb)/2:NaN,a=atr(c,FIB.entryAtrLength);let bullState=0,bearState=0,bullOrderIndex=-1,bearOrderIndex=-1,bullPull=-1,bearPull=-1,bullFib=NaN,bearFib=NaN,bullQ='',bearQ='';let latest:FibSignal|null=null;
 for(let i=1;i<c.length;i++){const x=c[i],p=c[i-1],sc=br?score(c.slice(0,i+1),ctx.dxy,x.time,bt,bb):{buy:0,sell:0},scSell=sr?score(c.slice(0,i+1),ctx.dxy,x.time,st,sb):{buy:0,sell:0};const bullOrderDetected=br&&x.close>=bmid&&p.close<p.open&&x.close>p.high&&(x.close-x.open)>=a[i]*0.50,bearOrderDetected=sr&&x.close<=smid&&p.close>p.open&&x.close<p.low&&(x.open-x.close)>=a[i]*0.50;if(bullOrderDetected){bullState=1;bullOrderIndex=i;bullPull=-1;bullFib=NaN;bullQ='';bearState=0;bearFib=NaN;bearQ='';}if(bearOrderDetected){bearState=1;bearOrderIndex=i;bearPull=-1;bearFib=NaN;bearQ='';bullState=0;bullFib=NaN;bullQ='';}
  if(bullState===1){if(x.low<=buyLevel(bt,bb,FIB.preferred)){bullState=2;bullPull=i;bullFib=buyLevel(bt,bb,FIB.preferred);bullQ='68.1% PREFERRED';}else if(x.low<=buyLevel(bt,bb,FIB.second)){bullState=2;bullPull=i;bullFib=buyLevel(bt,bb,FIB.second);bullQ='78.6% SECOND';}else if(x.low<=buyLevel(bt,bb,FIB.last)){bullState=2;bullPull=i;bullFib=buyLevel(bt,bb,FIB.last);bullQ='88% LAST RESORT';}}
  if(bearState===1){if(x.high>=sellLevel(st,sb,FIB.preferred)){bearState=2;bearPull=i;bearFib=sellLevel(st,sb,FIB.preferred);bearQ='68.1% PREFERRED';}else if(x.high>=sellLevel(st,sb,FIB.second)){bearState=2;bearPull=i;bearFib=sellLevel(st,sb,FIB.second);bearQ='78.6% SECOND';}else if(x.high>=sellLevel(st,sb,FIB.last)){bearState=2;bearPull=i;bearFib=sellLevel(st,sb,FIB.last);bearQ='88% LAST RESORT';}}
  if(bullState>=2&&i-bullPull>FIB.retestBars){bullState=0;bullFib=NaN;bullQ='';}if(bearState>=2&&i-bearPull>FIB.retestBars){bearState=0;bearFib=NaN;bearQ='';}
  const bullRet=bullState===2&&x.low<=bullFib&&x.close>bullFib,bearRet=bearState===2&&x.high>=bearFib&&x.close<bearFib;if(bullRet&&x.close>x.open&&x.close>p.high)bullState=3;if(bearRet&&x.close<x.open&&x.close<p.low)bearState=3;
  const conf=ctx.confirmation??[],confirmationTime=x.time+(ctx.confirmationOffsetMs??0),m5=atOrBefore(conf,confirmationTime),m5p=before(conf,confirmationTime),m5a=conf.length?atr(conf,FIB.entryAtrLength).at(-1):NaN,m5Bull=!!m5&&!!m5p&&Number.isFinite(m5a)&&m5.close>m5.open&&(m5.close-m5.open)>=m5a!*FIB.displacementATR&&m5.close>m5p.high,m5Bear=!!m5&&!!m5p&&Number.isFinite(m5a)&&m5.close<m5.open&&(m5.open-m5.close)>=m5a!*FIB.displacementATR&&m5.close<m5p.low;
  if(bullState===3&&m5Bull&&sc.buy>=FIB.minConfluence){const entry=bullFib,sl=buyLevel(bt,bb,FIB.stop),t1=buyLevel(bt,bb,FIB.tp1),t2=buyLevel(bt,bb,FIB.tp2),t3=buyLevel(bt,bb,FIB.tp3);latest={side:'BUY',entry,stopLoss:sl,takeProfit:t3,tp1:t1,tp2:t2,tp3:t3,confidence:sc.buy,quality:bullQ,reason:['Institutional order','Fib pullback','Fib retest','Candle confirmation','M5 bullish displacement',`Fib confluence ${sc.buy}/100`],state:'CONFIRMED',orderBar:bullOrderIndex,pullbackBar:bullPull};bullState=4;}
  if(bearState===3&&m5Bear&&scSell.sell>=FIB.minConfluence){const entry=bearFib,sl=sellLevel(st,sb,FIB.stop),t1=sellLevel(st,sb,FIB.tp1),t2=sellLevel(st,sb,FIB.tp2),t3=sellLevel(st,sb,FIB.tp3);latest={side:'SELL',entry,stopLoss:sl,takeProfit:t3,tp1:t1,tp2:t2,tp3:t3,confidence:scSell.sell,quality:bearQ,reason:['Institutional order','Fib pullback','Fib retest','Candle confirmation','M5 bearish displacement',`Fib confluence ${scSell.sell}/100`],state:'CONFIRMED',orderBar:bearOrderIndex,pullbackBar:bearPull};bearState=4;}
 }
 return latest;
}
